// <auto-generated />
using System;
using ControlEquiposComputo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlEquiposComputo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlEquiposComputo.Models.Clase", b =>
                {
                    b.Property<int>("ClaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaseID"));

                    b.Property<int>("DocenteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LaboratorioID")
                        .HasColumnType("int");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ClaseID");

                    b.HasIndex("DocenteID");

                    b.HasIndex("LaboratorioID");

                    b.ToTable("Clases");

                    b.HasData(
                        new
                        {
                            ClaseID = 1,
                            DocenteID = 1,
                            Fin = new DateTime(2024, 9, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física I"
                        },
                        new
                        {
                            ClaseID = 2,
                            DocenteID = 2,
                            Fin = new DateTime(2024, 9, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física II"
                        },
                        new
                        {
                            ClaseID = 3,
                            DocenteID = 3,
                            Fin = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 2,
                            NombreClase = "Programación Básica"
                        },
                        new
                        {
                            ClaseID = 4,
                            DocenteID = 1,
                            Fin = new DateTime(2024, 9, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física I"
                        },
                        new
                        {
                            ClaseID = 5,
                            DocenteID = 2,
                            Fin = new DateTime(2024, 9, 26, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física II"
                        },
                        new
                        {
                            ClaseID = 6,
                            DocenteID = 3,
                            Fin = new DateTime(2024, 9, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 2,
                            NombreClase = "Programación Básica"
                        },
                        new
                        {
                            ClaseID = 7,
                            DocenteID = 1,
                            Fin = new DateTime(2024, 9, 27, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física I"
                        },
                        new
                        {
                            ClaseID = 8,
                            DocenteID = 2,
                            Fin = new DateTime(2024, 9, 27, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 27, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Física II"
                        },
                        new
                        {
                            ClaseID = 9,
                            DocenteID = 3,
                            Fin = new DateTime(2024, 9, 27, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 2,
                            NombreClase = "Programación Básica"
                        },
                        new
                        {
                            ClaseID = 10,
                            DocenteID = 1,
                            Fin = new DateTime(2024, 9, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Química General"
                        },
                        new
                        {
                            ClaseID = 11,
                            DocenteID = 2,
                            Fin = new DateTime(2024, 9, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Química Orgánica"
                        },
                        new
                        {
                            ClaseID = 12,
                            DocenteID = 3,
                            Fin = new DateTime(2024, 9, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 2,
                            NombreClase = "Química Inorgánica"
                        },
                        new
                        {
                            ClaseID = 13,
                            DocenteID = 1,
                            Fin = new DateTime(2024, 9, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Matemáticas I"
                        },
                        new
                        {
                            ClaseID = 14,
                            DocenteID = 2,
                            Fin = new DateTime(2024, 9, 26, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 1,
                            NombreClase = "Matemáticas II"
                        },
                        new
                        {
                            ClaseID = 15,
                            DocenteID = 3,
                            Fin = new DateTime(2024, 9, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Inicio = new DateTime(2024, 9, 26, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            LaboratorioID = 2,
                            NombreClase = "Cálculo Diferencial"
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Docente", b =>
                {
                    b.Property<int>("DocenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocenteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("DocenteID");

                    b.ToTable("Docentes");

                    b.HasData(
                        new
                        {
                            DocenteID = 1,
                            Apellido = "Pérez",
                            Curso = "Matemáticas",
                            Email = "juan.perez@ejemplo.com",
                            Nombre = "Juan"
                        },
                        new
                        {
                            DocenteID = 2,
                            Apellido = "Gómez",
                            Curso = "Física",
                            Email = "maria.gomez@ejemplo.com",
                            Nombre = "María"
                        },
                        new
                        {
                            DocenteID = 3,
                            Apellido = "Fernández",
                            Curso = "Química",
                            Email = "luis.fernandez@ejemplo.com",
                            Nombre = "Luis"
                        },
                        new
                        {
                            DocenteID = 4,
                            Apellido = "Rodríguez",
                            Curso = "Biología",
                            Email = "ana.rodriguez@ejemplo.com",
                            Nombre = "Ana"
                        },
                        new
                        {
                            DocenteID = 5,
                            Apellido = "López",
                            Curso = "Historia",
                            Email = "carlos.lopez@ejemplo.com",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            DocenteID = 6,
                            Apellido = "Martínez",
                            Curso = "Geografía",
                            Email = "sofia.martinez@ejemplo.com",
                            Nombre = "Sofía"
                        },
                        new
                        {
                            DocenteID = 7,
                            Apellido = "Torres",
                            Curso = "Lengua",
                            Email = "miguel.torres@ejemplo.com",
                            Nombre = "Miguel"
                        },
                        new
                        {
                            DocenteID = 8,
                            Apellido = "Vega",
                            Curso = "Filosofía",
                            Email = "laura.vega@ejemplo.com",
                            Nombre = "Laura"
                        },
                        new
                        {
                            DocenteID = 9,
                            Apellido = "Ramírez",
                            Curso = "Educación Física",
                            Email = "jose.ramirez@ejemplo.com",
                            Nombre = "José"
                        },
                        new
                        {
                            DocenteID = 10,
                            Apellido = "Silva",
                            Curso = "Arte",
                            Email = "patricia.silva@ejemplo.com",
                            Nombre = "Patricia"
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("LaboratorioID")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NumeroEquipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("EquipoID");

                    b.HasIndex("LaboratorioID");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            EquipoID = 1,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "HP",
                            Modelo = "ProBook",
                            NumeroEquipo = "EQF-01"
                        },
                        new
                        {
                            EquipoID = 2,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Dell",
                            Modelo = "Inspiron",
                            NumeroEquipo = "EQF-02"
                        },
                        new
                        {
                            EquipoID = 3,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Lenovo",
                            Modelo = "ThinkPad",
                            NumeroEquipo = "EQF-03"
                        },
                        new
                        {
                            EquipoID = 4,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Asus",
                            Modelo = "ZenBook",
                            NumeroEquipo = "EQF-04"
                        },
                        new
                        {
                            EquipoID = 5,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Acer",
                            Modelo = "Aspire",
                            NumeroEquipo = "EQF-05"
                        },
                        new
                        {
                            EquipoID = 6,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "HP",
                            Modelo = "Pavilion",
                            NumeroEquipo = "EQF-06"
                        },
                        new
                        {
                            EquipoID = 7,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Apple",
                            Modelo = "MacBook Pro",
                            NumeroEquipo = "EQF-07"
                        },
                        new
                        {
                            EquipoID = 8,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Samsung",
                            Modelo = "Chromebook",
                            NumeroEquipo = "EQF-08"
                        },
                        new
                        {
                            EquipoID = 9,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Toshiba",
                            Modelo = "Satellite",
                            NumeroEquipo = "EQF-09"
                        },
                        new
                        {
                            EquipoID = 10,
                            Estado = "Operativo",
                            LaboratorioID = 1,
                            Marca = "Dell",
                            Modelo = "XPS",
                            NumeroEquipo = "EQF-10"
                        },
                        new
                        {
                            EquipoID = 11,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "HP",
                            Modelo = "EliteBook",
                            NumeroEquipo = "EQI-01"
                        },
                        new
                        {
                            EquipoID = 12,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Dell",
                            Modelo = "Latitude",
                            NumeroEquipo = "EQI-02"
                        },
                        new
                        {
                            EquipoID = 13,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Lenovo",
                            Modelo = "IdeaPad",
                            NumeroEquipo = "EQI-03"
                        },
                        new
                        {
                            EquipoID = 14,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Asus",
                            Modelo = "VivoBook",
                            NumeroEquipo = "EQI-04"
                        },
                        new
                        {
                            EquipoID = 15,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Acer",
                            Modelo = "Nitro",
                            NumeroEquipo = "EQI-05"
                        },
                        new
                        {
                            EquipoID = 16,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "HP",
                            Modelo = "Omen",
                            NumeroEquipo = "EQI-06"
                        },
                        new
                        {
                            EquipoID = 17,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Apple",
                            Modelo = "MacBook Air",
                            NumeroEquipo = "EQI-07"
                        },
                        new
                        {
                            EquipoID = 18,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Samsung",
                            Modelo = "Galaxy Book",
                            NumeroEquipo = "EQI-08"
                        },
                        new
                        {
                            EquipoID = 19,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Toshiba",
                            Modelo = "Tecra",
                            NumeroEquipo = "EQI-09"
                        },
                        new
                        {
                            EquipoID = 20,
                            Estado = "Operativo",
                            LaboratorioID = 2,
                            Marca = "Dell",
                            Modelo = "Precision",
                            NumeroEquipo = "EQI-10"
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("EstudianteID");

                    b.ToTable("Estudiantes");

                    b.HasData(
                        new
                        {
                            EstudianteID = 1,
                            Apellido = "Ramírez",
                            Email = "carlos.ramirez@ejemplo.com",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            EstudianteID = 2,
                            Apellido = "García",
                            Email = "lucia.garcia@ejemplo.com",
                            Nombre = "Lucía"
                        },
                        new
                        {
                            EstudianteID = 3,
                            Apellido = "Méndez",
                            Email = "pedro.mendez@ejemplo.com",
                            Nombre = "Pedro"
                        },
                        new
                        {
                            EstudianteID = 4,
                            Apellido = "Martínez",
                            Email = "sofia.martinez@ejemplo.com",
                            Nombre = "Sofía"
                        },
                        new
                        {
                            EstudianteID = 5,
                            Apellido = "Gómez",
                            Email = "andres.gomez@ejemplo.com",
                            Nombre = "Andrés"
                        },
                        new
                        {
                            EstudianteID = 6,
                            Apellido = "Ruiz",
                            Email = "isabel.ruiz@ejemplo.com",
                            Nombre = "Isabel"
                        },
                        new
                        {
                            EstudianteID = 7,
                            Apellido = "López",
                            Email = "javier.lopez@ejemplo.com",
                            Nombre = "Javier"
                        },
                        new
                        {
                            EstudianteID = 8,
                            Apellido = "Sánchez",
                            Email = "natalia.sanchez@ejemplo.com",
                            Nombre = "Natalia"
                        },
                        new
                        {
                            EstudianteID = 9,
                            Apellido = "Díaz",
                            Email = "gabriel.diaz@ejemplo.com",
                            Nombre = "Gabriel"
                        },
                        new
                        {
                            EstudianteID = 10,
                            Apellido = "Fernández",
                            Email = "maria.fernandez@ejemplo.com",
                            Nombre = "María"
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Incidente", b =>
                {
                    b.Property<int>("IncidenteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenteID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaIncidente")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsoEquipoID")
                        .HasColumnType("int");

                    b.HasKey("IncidenteID");

                    b.HasIndex("UsoEquipoID");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Laboratorio", b =>
                {
                    b.Property<int>("LaboratorioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratorioID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreLaboratorio")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("LaboratorioID");

                    b.ToTable("Laboratorios");

                    b.HasData(
                        new
                        {
                            LaboratorioID = 1,
                            Capacidad = 30,
                            NombreLaboratorio = "Laboratorio de Física",
                            Ubicacion = "Edificio A, Piso 1"
                        },
                        new
                        {
                            LaboratorioID = 2,
                            Capacidad = 40,
                            NombreLaboratorio = "Laboratorio de Informática",
                            Ubicacion = "Edificio C, Piso 3"
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Mantenimiento", b =>
                {
                    b.Property<int>("MantenimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MantenimientoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("TecnicoID")
                        .HasColumnType("int");

                    b.HasKey("MantenimientoID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("TecnicoID");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Tecnico", b =>
                {
                    b.Property<int>("TecnicoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TecnicoID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("TecnicoID");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.UsoEquipo", b =>
                {
                    b.Property<int>("UsoEquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsoEquipoID"));

                    b.Property<string>("Actividad")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("ClaseID")
                        .HasColumnType("int");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsoEquipoID");

                    b.HasIndex("ClaseID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("EstudianteID");

                    b.ToTable("UsoEquipos");

                    b.HasData(
                        new
                        {
                            UsoEquipoID = 1,
                            Actividad = "Actividad 1",
                            ClaseID = 7,
                            EquipoID = 19,
                            EstudianteID = 9,
                            FechaAsignacion = new DateTime(2024, 9, 25, 4, 17, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 2,
                            Actividad = "Actividad 2",
                            ClaseID = 10,
                            EquipoID = 1,
                            EstudianteID = 9,
                            FechaAsignacion = new DateTime(2024, 9, 25, 1, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 3,
                            Actividad = "Actividad 3",
                            ClaseID = 14,
                            EquipoID = 2,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 26, 8, 49, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 4,
                            Actividad = "Actividad 4",
                            ClaseID = 10,
                            EquipoID = 7,
                            EstudianteID = 5,
                            FechaAsignacion = new DateTime(2024, 9, 26, 2, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 5,
                            Actividad = "Actividad 5",
                            ClaseID = 8,
                            EquipoID = 19,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 0, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 6,
                            Actividad = "Actividad 6",
                            ClaseID = 12,
                            EquipoID = 7,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 26, 14, 34, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 7,
                            Actividad = "Actividad 7",
                            ClaseID = 11,
                            EquipoID = 6,
                            EstudianteID = 9,
                            FechaAsignacion = new DateTime(2024, 9, 26, 13, 21, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 8,
                            Actividad = "Actividad 8",
                            ClaseID = 8,
                            EquipoID = 20,
                            EstudianteID = 1,
                            FechaAsignacion = new DateTime(2024, 9, 25, 5, 59, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 9,
                            Actividad = "Actividad 9",
                            ClaseID = 10,
                            EquipoID = 17,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 25, 9, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 10,
                            Actividad = "Actividad 10",
                            ClaseID = 6,
                            EquipoID = 19,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 25, 22, 3, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 11,
                            Actividad = "Actividad 11",
                            ClaseID = 6,
                            EquipoID = 2,
                            EstudianteID = 2,
                            FechaAsignacion = new DateTime(2024, 9, 26, 8, 13, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 12,
                            Actividad = "Actividad 12",
                            ClaseID = 8,
                            EquipoID = 3,
                            EstudianteID = 7,
                            FechaAsignacion = new DateTime(2024, 9, 26, 12, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 13,
                            Actividad = "Actividad 13",
                            ClaseID = 5,
                            EquipoID = 13,
                            EstudianteID = 1,
                            FechaAsignacion = new DateTime(2024, 9, 26, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 14,
                            Actividad = "Actividad 14",
                            ClaseID = 13,
                            EquipoID = 7,
                            EstudianteID = 1,
                            FechaAsignacion = new DateTime(2024, 9, 26, 18, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 15,
                            Actividad = "Actividad 15",
                            ClaseID = 12,
                            EquipoID = 19,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 18, 1, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 16,
                            Actividad = "Actividad 16",
                            ClaseID = 6,
                            EquipoID = 20,
                            EstudianteID = 9,
                            FechaAsignacion = new DateTime(2024, 9, 25, 0, 21, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 17,
                            Actividad = "Actividad 17",
                            ClaseID = 12,
                            EquipoID = 7,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 25, 10, 13, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 18,
                            Actividad = "Actividad 18",
                            ClaseID = 10,
                            EquipoID = 7,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 11, 58, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 19,
                            Actividad = "Actividad 19",
                            ClaseID = 5,
                            EquipoID = 6,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 6, 46, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 20,
                            Actividad = "Actividad 20",
                            ClaseID = 6,
                            EquipoID = 20,
                            EstudianteID = 3,
                            FechaAsignacion = new DateTime(2024, 9, 26, 4, 19, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 21,
                            Actividad = "Actividad 21",
                            ClaseID = 5,
                            EquipoID = 9,
                            EstudianteID = 2,
                            FechaAsignacion = new DateTime(2024, 9, 25, 13, 42, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 22,
                            Actividad = "Actividad 22",
                            ClaseID = 10,
                            EquipoID = 3,
                            EstudianteID = 7,
                            FechaAsignacion = new DateTime(2024, 9, 25, 7, 49, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 23,
                            Actividad = "Actividad 23",
                            ClaseID = 15,
                            EquipoID = 11,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 3, 41, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 24,
                            Actividad = "Actividad 24",
                            ClaseID = 14,
                            EquipoID = 4,
                            EstudianteID = 10,
                            FechaAsignacion = new DateTime(2024, 9, 25, 17, 7, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 25,
                            Actividad = "Actividad 25",
                            ClaseID = 13,
                            EquipoID = 15,
                            EstudianteID = 5,
                            FechaAsignacion = new DateTime(2024, 9, 26, 15, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 26,
                            Actividad = "Actividad 26",
                            ClaseID = 1,
                            EquipoID = 11,
                            EstudianteID = 2,
                            FechaAsignacion = new DateTime(2024, 9, 26, 11, 12, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 27,
                            Actividad = "Actividad 27",
                            ClaseID = 1,
                            EquipoID = 15,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 5, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 28,
                            Actividad = "Actividad 28",
                            ClaseID = 8,
                            EquipoID = 5,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 22, 8, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 29,
                            Actividad = "Actividad 29",
                            ClaseID = 6,
                            EquipoID = 11,
                            EstudianteID = 7,
                            FechaAsignacion = new DateTime(2024, 9, 26, 22, 53, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 30,
                            Actividad = "Actividad 30",
                            ClaseID = 14,
                            EquipoID = 9,
                            EstudianteID = 3,
                            FechaAsignacion = new DateTime(2024, 9, 26, 16, 3, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 31,
                            Actividad = "Actividad 31",
                            ClaseID = 14,
                            EquipoID = 5,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 6, 31, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 32,
                            Actividad = "Actividad 32",
                            ClaseID = 8,
                            EquipoID = 11,
                            EstudianteID = 5,
                            FechaAsignacion = new DateTime(2024, 9, 25, 12, 57, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 33,
                            Actividad = "Actividad 33",
                            ClaseID = 6,
                            EquipoID = 17,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 26, 12, 14, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 34,
                            Actividad = "Actividad 34",
                            ClaseID = 9,
                            EquipoID = 7,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 25, 9, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 35,
                            Actividad = "Actividad 35",
                            ClaseID = 10,
                            EquipoID = 17,
                            EstudianteID = 10,
                            FechaAsignacion = new DateTime(2024, 9, 26, 3, 13, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 36,
                            Actividad = "Actividad 36",
                            ClaseID = 2,
                            EquipoID = 7,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 26, 1, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 37,
                            Actividad = "Actividad 37",
                            ClaseID = 9,
                            EquipoID = 6,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 20, 38, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 38,
                            Actividad = "Actividad 38",
                            ClaseID = 2,
                            EquipoID = 1,
                            EstudianteID = 3,
                            FechaAsignacion = new DateTime(2024, 9, 26, 17, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 39,
                            Actividad = "Actividad 39",
                            ClaseID = 9,
                            EquipoID = 8,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 25, 8, 16, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 40,
                            Actividad = "Actividad 40",
                            ClaseID = 11,
                            EquipoID = 14,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 4, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 41,
                            Actividad = "Actividad 41",
                            ClaseID = 3,
                            EquipoID = 20,
                            EstudianteID = 4,
                            FechaAsignacion = new DateTime(2024, 9, 25, 7, 54, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 42,
                            Actividad = "Actividad 42",
                            ClaseID = 13,
                            EquipoID = 6,
                            EstudianteID = 8,
                            FechaAsignacion = new DateTime(2024, 9, 26, 13, 56, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 43,
                            Actividad = "Actividad 43",
                            ClaseID = 9,
                            EquipoID = 6,
                            EstudianteID = 10,
                            FechaAsignacion = new DateTime(2024, 9, 26, 22, 46, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 44,
                            Actividad = "Actividad 44",
                            ClaseID = 5,
                            EquipoID = 6,
                            EstudianteID = 2,
                            FechaAsignacion = new DateTime(2024, 9, 26, 5, 58, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 45,
                            Actividad = "Actividad 45",
                            ClaseID = 2,
                            EquipoID = 12,
                            EstudianteID = 1,
                            FechaAsignacion = new DateTime(2024, 9, 26, 6, 46, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 46,
                            Actividad = "Actividad 46",
                            ClaseID = 13,
                            EquipoID = 3,
                            EstudianteID = 10,
                            FechaAsignacion = new DateTime(2024, 9, 26, 16, 35, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 47,
                            Actividad = "Actividad 47",
                            ClaseID = 14,
                            EquipoID = 19,
                            EstudianteID = 6,
                            FechaAsignacion = new DateTime(2024, 9, 26, 7, 6, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 48,
                            Actividad = "Actividad 48",
                            ClaseID = 13,
                            EquipoID = 4,
                            EstudianteID = 2,
                            FechaAsignacion = new DateTime(2024, 9, 25, 14, 42, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 49,
                            Actividad = "Actividad 49",
                            ClaseID = 8,
                            EquipoID = 6,
                            EstudianteID = 7,
                            FechaAsignacion = new DateTime(2024, 9, 26, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UsoEquipoID = 50,
                            Actividad = "Actividad 50",
                            ClaseID = 13,
                            EquipoID = 19,
                            EstudianteID = 7,
                            FechaAsignacion = new DateTime(2024, 9, 25, 5, 7, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Clase", b =>
                {
                    b.HasOne("ControlEquiposComputo.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEquiposComputo.Models.Laboratorio", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Equipo", b =>
                {
                    b.HasOne("ControlEquiposComputo.Models.Laboratorio", "Laboratorio")
                        .WithMany()
                        .HasForeignKey("LaboratorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Incidente", b =>
                {
                    b.HasOne("ControlEquiposComputo.Models.UsoEquipo", "UsoEquipo")
                        .WithMany()
                        .HasForeignKey("UsoEquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsoEquipo");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Mantenimiento", b =>
                {
                    b.HasOne("ControlEquiposComputo.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEquiposComputo.Models.Tecnico", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.UsoEquipo", b =>
                {
                    b.HasOne("ControlEquiposComputo.Models.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEquiposComputo.Models.Equipo", "Equipo")
                        .WithMany("UsoEquipos")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlEquiposComputo.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Equipo");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("ControlEquiposComputo.Models.Equipo", b =>
                {
                    b.Navigation("UsoEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
